Реализованы и покрыты тестами классы Person и CustomDigitComparator
Wesper/java-reboot pull request #4
Opened 2023-11-06 06:40 UTC by Wesper

2023-11-10 13:51 UTC, rsmitt commented on module04/src/main/java/ru/sberbank/edu/Person.java
> +        return Objects.hash(name, city, age);
у вас equals сравнивает без учета регистра, все приводится в нижний, но hashCode учитывает регистр в результате 2 объекта по equals будут равны но по hashCode не равны. Это приведет к коллизиям. Если по equals объекты равны, то hashCode должны тоже быть равны,  если у объектов hashCode равны, это не означает что и equals будут равны. Можно еще раз на практике обсудить если есть вопросы.

2023-11-10 13:52 UTC, rsmitt commented on module04/src/main/java/ru/sberbank/edu/Person.java
> +        return Objects.hash(name, city, age);
Приведите в hashCode city и name в нижний или верхний регистр

2023-11-10 13:53 UTC, rsmitt requested changes
Прошу поправить регистр в hashCode

2023-11-12 14:16 UTC, Wesper commented on module04/src/main/java/ru/sberbank/edu/Person.java
> +        return Objects.hash(name, city, age);
Спасибо, исправил

2023-11-18 12:45 UTC, rsmitt approved these changes

2023-11-19 09:39 UTC, merged